name: duplicates_detector
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  excel: 2.0.4
  reactive_forms: ^14.2.0
  reactive_file_picker: ^0.12.0
  file_picker: ^5.2.5
  flutter_bloc: ^8.1.2
  yaru: ^0.7.0
  flutter_highlight: ^0.7.0
  clipboard: ^0.1.3
dev_dependencies:
  test: ^1.23.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/